# Generated by Django 3.1.1 on 2020-11-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField(max_length=350)),
                ('product_image', models.TextField(blank=True, max_length=200)),
                ('product_isAvailable', models.BooleanField(default=True)),
                ('product_quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
