# Generated by Django 3.1.1 on 2020-09-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstapp',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='products/'),
        ),
    ]
